### ISSUE TITLE
LS Customs Vehicle Spawner

### ISSUE THREAD

**Issue by shelby0341** [DSRP-Inc/DSRP_Tickets#6]
**Reference ticket number:**

**Reporting persons Discord name:**
shelby0341

**Clearly describe the bug:**
There's a vehicle spawner in the parking lot of LS Customs right next to the camper trailer, and when you take one out, it spawns between the camper and the storefront building.

**Describe the steps to reproduce:**
Take out a vehicle next to the camper in LS Customs parking lot

**What is the expected behavior?**
Should be moved to somewhere with more clearance.

**Screenshots/clips:**

**Comment by Daemon53** [comment]
@IngleArf how did the trailer get back in there?

**Comment by IngleArf** [comment]
@Daemon53 it must have been when we transferred over to our current host, the old edit of the trees must still be in there. I can change it

**Comment by IngleArf** [comment]
Removed this last night. Was not able to check because restart was not until today. 

Will double check and circle back to this issue

**Comment by IngleArf** [comment]
This issue is solved

**Comment by shelby0341** [comment]
The prompt is still there, unable to pull anything out of it but you can still see the prompt to.

![Image](https://github.com/DSRP-Inc/DSRP_Tickets/assets/84191689/c4cc04ba-9beb-469d-b2e4-4423b36b5bdc)

**Comment by shelby0341** [comment]
Can confirm the prompt is gone, moving to complete
